import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import Dashboard from './pages/Dashboard';
import PostList from './pages/PostList';
import CreatePost from './pages/CreatePost';
import BlankLayout from './layouts/BlankLayout';
import Login from './pages/Login';
import NotFound from './pages/NotFound';

const authSST = (nextState, replace, next) => {
  const token = sessionStorage.getItem('token');
  if (token && token !== 'null') {
    next();
  } else {
    replace({
      pathname: '/login',
      state: { nextPathname: nextState.location.pathname },
    });
    next();
  }
};

const autoGeneratedRoutes = [
  {
    path: '/login',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: {
      component: Login,
    },
  },
  {
    path: '/post',
    onEnter: authSST,
    childRoutes: [
      {
        path: 'list',
        childRoutes: [],
        component: PostList,
      },
      {
        path: 'create',
        childRoutes: [],
        component: CreatePost,
      },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: PostList,
    },
  },
  {
    path: '/',
    onEnter: authSST,
    childRoutes: [
      {
        path: '*',
        childRoutes: [],
        component: NotFound,
      },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: Dashboard,
    },
  },
];

const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
